# Generated by Django 5.2 on 2025-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csfd_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csfd_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('actors', models.ManyToManyField(related_name='films', to='core.actor')),
            ],
        ),
    ]
